### ISSUE TITLE
Visualise the generated motions时的异常

### ISSUE THREAD

**Issue by QiFuChina** [TheTempAccount/Co-Speech-Motion-Generation#11]
根据文档配置到`Visualise the generated motions` 时，产生如下信息：
(csmg) xht@xht-Z590-GAMING-X:~/SourceCode/Co-Speech-Motion-Generation/src$ bash visualise.sh
making video
Traceback (most recent call last):
  File "visualise/visualise_generation_res.py", line 36, in <module>
    from visualise.draw_utils import *
  File "/home/xht/SourceCode/Co-Speech-Motion-Generation/src/visualise/draw_utils.py", line 5, in <module>
    os.environ['OMP_NUM_THREADS']=1 #TODO: test
  File "/home/xht/.conda/envs/csmg/lib/python3.7/os.py", line 686, in __setitem__
    value = self.encodevalue(value)
  File "/home/xht/.conda/envs/csmg/lib/python3.7/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int

已经把`/config`下的json文件和`/pose_dataset/ckpt/freeMo.json`文件中的`data_root`都修改为了本地路径，在`Visualise the generated motions` 失败后尝试直接`Generate motions for a speaker in test_audios`，提示找不到对应的`freeMo.json`文件：
(csmg) xht@xht-Z590-GAMING-X:~/SourceCode/Co-Speech-Motion-Generation/src$ bash infer.sh  \
> pose_dataset/ckpt/ckpt-99.pth \
> pose_dataset/ckpt/freeMo.json \
> test \
> Enric_Sala
/home/xht/SourceCode/Co-Speech-Motion-Generation/src/nets/graph_definition.py:35: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  [0, 9, 11]
Traceback (most recent call last):
  File "scripts/infer.py", line 150, in <module>
    main()
  File "scripts/infer.py", line 140, in main
    config = load_JsonConfig(args.config_file)
  File "/home/xht/SourceCode/Co-Speech-Motion-Generation/src/trainer/config.py", line 15, in load_JsonConfig
    with open(json_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pose_dataset/ckpt/freeMo.json'

**Comment by TheTempAccount** [comment]
看一下这个json文件的绝对路径是啥，然后在运行命令里替换一下。

**Comment by QiFuChina** [comment]
谢谢，另外我还有一些地方不太理解
**1、在执行`bash visualese.sh`后得到的结果是**
_making video
Traceback (most recent call last):
File "visualise/visualise_generation_res.py", line 36, in
from visualise.draw_utils import *
File "/home/xht/SourceCode/Co-Speech-Motion-Generation/src/visualise/draw_utils.py", line 5, in
os.environ['OMP_NUM_THREADS']=1 #TODO: test
File "/home/xht/.conda/envs/csmg/lib/python3.7/os.py", line 686, in setitem
value = self.encodevalue(value)
File "/home/xht/.conda/envs/csmg/lib/python3.7/os.py", line 756, in encode
raise TypeError("str expected, not %s" % type(value).name)
TypeError: str expected, not int_
2、像参数`<post_fix>`是指输入什么？
3、参数 `<speaker_name>`尝试在命令行输入单独的姓名显示如下
_******
Bill_Gates
/home/xht/SourceCode/Co-Speech-Motion-Generation/src/nets/graph_definition.py:35: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  [0, 9, 11]
init model...
using rnn encoder
non iterative decoder
init dataloader...
['ozfGHONpdTA', '.DS_Store']
Traceback (most recent call last):
  File "scripts/infer.py", line 150, in <module>
    main()
  File "scripts/infer.py", line 145, in main
    infer_set, infer_loader, norm_stats = init_dataloader(config.Data.data_root, args.speakers, args, config)
  File "scripts/infer.py", line 77, in init_dataloader
    feat_method=config.Data.aud.feat_method
  File "/home/xht/SourceCode/Co-Speech-Motion-Generation/src/data_utils/dataloader_torch.py", line 347, in __init__
    seqs = [s for s in os.listdir(vid_pth) if (s.startswith('clip'))]
FileNotFoundError: [Errno 2] No such file or directory: '/home/xht/SourceCode/Co-Speech-Motion-Generation/pose_dataset/videos/Bill_Gates/clips/ozfGHONpdTA/images/half/val'_

或者是带文件路径格式的姓名
_******
/home/xht/SourceCode/Co-Speech-Motion-Generation/pose_dataset/videos/Bill_Gates
/home/xht/SourceCode/Co-Speech-Motion-Generation/src/nets/graph_definition.py:35: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  [0, 9, 11]
init model...
using rnn encoder
non iterative decoder
init dataloader...
['palA7Mg_AFs', '6Af6b_wyiwI', 'ozfGHONpdTA', '81Ub0SMxZQo', 'jiUKpX09zo4', 'Jaf-f12Zn7I', '.DS_Store']
Traceback (most recent call last):
  File "scripts/infer.py", line 150, in <module>
    main()
  File "scripts/infer.py", line 145, in main
    infer_set, infer_loader, norm_stats = init_dataloader(config.Data.data_root, args.speakers, args, config)
  File "scripts/infer.py", line 77, in init_dataloader
    feat_method=config.Data.aud.feat_method
  File "/home/xht/SourceCode/Co-Speech-Motion-Generation/src/data_utils/dataloader_torch.py", line 347, in __init__
    seqs = [s for s in os.listdir(vid_pth) if (s.startswith('clip'))]
NotADirectoryError: [Errno 20] Not a directory: '/home/xht/SourceCode/Co-Speech-Motion-Generation/pose_dataset/videos/Bill_Gates/clips/.DS_Store/images/half/val'_
这些问题是因为我在visualise motions时不成功导致的么？
